# Get All Wishlist
GET https://tiwi-bagus.netlify.app:3001/wishes HTTP/1.1
Content-Type: application/json

###

# Create a wish
POST https://tiwi-bagus.netlify.app:3001/wishes HTTP/1.1
Content-Type: application/json

{
    "name": "Harry Potter",
    "message": "fdsfsdfsffs"
}

###